
package ws_tomedos;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import ru.ibs.fss.ln.ws.fileoperationsln.FileOperationsLnUserGetNewLNNumRangeOut;
import ru.ibs.fss.ln.ws.fileoperationsln.WSResult;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IWebService", targetNamespace = "http://WS_ToMedOs/")
@XmlSeeAlso({
    ru.ibs.fss.ln.ws.fileoperationsln.ObjectFactory.class,
    ws_tomedos.ObjectFactory.class
})
public interface IWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns ru.ibs.fss.ln.ws.fileoperationsln.WSResult
     * @throws SOAPExceptionException
     */
    @WebMethod(operationName = "SetDisabilityDocument")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SetDisabilityDocument", targetNamespace = "http://WS_ToMedOs/", className = "ws_tomedos.SetDisabilityDocument")
    @ResponseWrapper(localName = "SetDisabilityDocumentResponse", targetNamespace = "http://WS_ToMedOs/", className = "ws_tomedos.SetDisabilityDocumentResponse")
    @Action(input = "http://WS_ToMedOs/IWebService/SetDisabilityDocumentRequest", output = "http://WS_ToMedOs/IWebService/SetDisabilityDocumentResponse", fault = {
        @FaultAction(className = SOAPExceptionException.class, value = "http://WS_ToMedOs/IWebService/SetDisabilityDocument/Fault/SOAPException_Exception")
    })
    public WSResult setDisabilityDocument(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws SOAPExceptionException
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod(operationName = "GetCalculaton")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetCalculaton", targetNamespace = "http://WS_ToMedOs/", className = "ws_tomedos.GetCalculaton")
    @ResponseWrapper(localName = "GetCalculatonResponse", targetNamespace = "http://WS_ToMedOs/", className = "ws_tomedos.GetCalculatonResponse")
    @Action(input = "http://WS_ToMedOs/IWebService/GetCalculatonRequest", output = "http://WS_ToMedOs/IWebService/GetCalculatonResponse")
    public int getCalculaton(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns ru.ibs.fss.ln.ws.fileoperationsln.FileOperationsLnUserGetNewLNNumRangeOut
     * @throws SOAPExceptionException
     */
    @WebMethod(operationName = "GetRangeNumbers")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetRangeNumbers", targetNamespace = "http://WS_ToMedOs/", className = "ws_tomedos.GetRangeNumbers")
    @ResponseWrapper(localName = "GetRangeNumbersResponse", targetNamespace = "http://WS_ToMedOs/", className = "ws_tomedos.GetRangeNumbersResponse")
    @Action(input = "http://WS_ToMedOs/IWebService/GetRangeNumbersRequest", output = "http://WS_ToMedOs/IWebService/GetRangeNumbersResponse", fault = {
        @FaultAction(className = SOAPExceptionException.class, value = "http://WS_ToMedOs/IWebService/GetRangeNumbers/Fault/SOAPException_Exception")
    })
    public FileOperationsLnUserGetNewLNNumRangeOut getRangeNumbers(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1)
        throws SOAPExceptionException
    ;

}
